// Permission keys (DB-stored). Kept in sync with packages/shared-types.
export const PERMISSIONS = [
  'manage_restaurant_settings',
  'view_dashboard',
  'manage_staff',
  'manage_roles',
  'manage_permissions',
  'manage_categories',
  'manage_menu_items',
  'manage_inventory',
  'view_inventory',
  'create_order',
  'update_order',
  'cancel_order',
  'view_orders',
  'send_order_to_kitchen',
  'update_order_status',
  'generate_invoice',
  'apply_discount',
  'receive_payment',
  'print_receipt',
  'manage_customers',
  'view_reports',
  'search_invoices',
  'view_recent_activities',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

// Default role → permission mapping for the first version (seed).
export const ROLE_PERMISSIONS: Record<string, PermissionKey[] | 'ALL'> = {
  Admin: 'ALL',
  Manager: [
    'view_dashboard',
    'manage_categories',
    'manage_menu_items',
    'view_inventory',
    'create_order',
    'update_order',
    'cancel_order',
    'view_orders',
    'send_order_to_kitchen',
    'update_order_status',
    'generate_invoice',
    'apply_discount',
    'receive_payment',
    'print_receipt',
    'manage_customers',
    'view_reports',
    'search_invoices',
    'view_recent_activities',
  ],
  Cashier: [
    'view_orders',
    'generate_invoice',
    'receive_payment',
    'print_receipt',
    'search_invoices',
    'manage_customers',
  ],
  Waiter: ['create_order', 'update_order', 'view_orders', 'send_order_to_kitchen'],
  Kitchen: ['view_orders', 'update_order_status'],
  Inventory: ['manage_inventory', 'view_inventory'],
};
